//
//  NSPasteboardItem++.swift
//  ClipKit
//
//  Created by samara on 29.06.2025.
//

import AppKit.NSPasteboard

// MARK: - Custom Types
extension NSPasteboard.PasteboardType {
	// Always ignored
	static public let mainBundle = 		NSPasteboard.PasteboardType(Bundle.main.bundleIdentifier!)
	static public let remoteClipboard = NSPasteboard.PasteboardType("com.apple.is-remote-clipboard")
	// Apps to ignore by default
	static public let maccy = 			NSPasteboard.PasteboardType("org.p0deje.Maccy")
	static public let clipper = 		NSPasteboard.PasteboardType("thewonderofyou.Clipper")
	static public let onePassword = 	NSPasteboard.PasteboardType("com.agilebits.onepassword")
	static public let keeWeb = 			NSPasteboard.PasteboardType("net.antelle.keeweb")
	// Transient types to ignore by default
	static public let transient = 		NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
	static public let transient2 = 		NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType")
	static public let transient3 = 		NSPasteboard.PasteboardType("com.typeit4me.clipping")
	static public let autoGenerated = 	NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
	// Confidential types to ignore by default
	static public let confidential = 	NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
}

// MARK: - Grouped Types
extension NSPasteboard.PasteboardType {
	/// Always ignored.
	static public let ignoredTypes: [NSPasteboard.PasteboardType] = [
		.mainBundle,
		.remoteClipboard
	]
	/// Only ignored if the default is true.
	static public let appTypes: [NSPasteboard.PasteboardType] = [
		.maccy,
		.clipper,
		.onePassword,
		.keeWeb
	]
	/// Only ignored if the default is true.
	static public let transientTypes: [NSPasteboard.PasteboardType] = [
		.transient,
		.transient2,
		.transient3,
		.autoGenerated
	]
	/// Only ignored if the default is true.
	static public let confidentialTypes: [NSPasteboard.PasteboardType] = [
		.confidential
	]
	/// Supported types for view dragging.
	static public let supportedDragTypes: [NSPasteboard.PasteboardType] = [
		.string,
		.png,
		.URL,
		.fileURL,
		.tiff,
		.font,
		.html,
		.rtf,
		.rtfd
	]
}
