name: Create Bug Report
description: Report a bug or crash.
title: '[Bug] '
labels:
  - bug

body:
  - type: markdown
    attributes:
      value: >-
        Make sure you read the [Code of
        Conduct](https://github.com/khcrysalis/Copyboard/blob/main/CODE_OF_CONDUCT.md)
        before making an issue, and make sure there aren't already the same bug
        reported.

  - type: textarea
    id: text
    attributes:
      label: Report
    validations:
      required: true

  - type: checkboxes
    id: agreement
    attributes:
      label: Request Agreement
      options:
        - label: I have read the requirements for opening an issue above
          required: true

  - type: checkboxes
    id: agreement2
    attributes:
      label: Contributor Checks
      options:
        - label: I am willing to fix this bug myself
          required: false
