//
//  AdditionalTypes.swift
//  DataTypesKit
//
//  Created by Lakhan Lothiyi on 14/01/2025.
//

// please add types to this array
extension DataType {
	static var _additionalTypes: [DataType] {
		[
			.remoteClipboard,
			.xcodeSourceCode,
			
			.autoGenerated, .concealed, .transient, .modified,
			
			.fromMaccy, .fromClipper,
			
			.microsoftObjectLink, .microsoftLinkSource
		]
	}
}


// put types here
public extension DataType {
	static let remoteClipboard: DataType = .init(identifier: "com.apple.is-remote-clipboard", description: "Remote Clipboard")
	static let xcodeSourceCode: DataType = .init(identifier: "dyn.ah62d4rv4gu8zg55zsmv0nvperf4g86varvu0635zqfx0nkdsqf00nkduqf31k3pcr7u1e3basv61a3k", description: "Xcode Source")
	
	static let autoGenerated: DataType = .init(identifier: "org.nspasteboard.AutoGeneratedType", description: "Auto Generated")
	static let concealed: DataType = .init(identifier: "org.nspasteboard.ConcealedType", description: "Concealed")
	static let transient: DataType = .init(identifier: "org.nspasteboard.TransientType", description: "Transcient")
	
	static let modified: DataType = .init(identifier: "x.nspasteboard.ModifiedType", description: "Modified")
	
	static let fromMaccy: DataType = .init(identifier:  "org.p0deje.Maccy", description: "From Maccy")
	static let fromClipper: DataType = .init(identifier: "thewonderofyou.Clipper", description: "From Clipper")
	
	static let microsoftObjectLink: DataType = .init(identifier:  "com.microsoft.ObjectLink", description: "Microsoft Object Link")
	static let microsoftLinkSource: DataType = .init(identifier: "com.microsoft.Link-Source", description: "Microsoft Link Source")
}
