name: Nightly CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  nightly:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Select Xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer

      - name: Build Artifacts
        run: make

      - name: Get short SHA
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-6)" >> $GITHUB_ENV

      - name: Release Nightly
        uses: andelf/nightly-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHORT_SHA: ${{ env.SHORT_SHA }}
        with:
          body: |
            >  [!NOTE]
            > Auto-updating is not yet implemented! Will be in a future release, for now you will need to update manually.
            
            **Commit:** [${{ env.SHORT_SHA }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
          files: packages/Copyboard.zip
          name: Copyboard Nightly @ ${{ env.SHORT_SHA }}
